# Generated by Django 3.2.7 on 2021-12-16 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cs_api', '0002_auto_20211215_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudstackUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300)),
                ('apiKey', models.CharField(max_length=86)),
                ('secretKey', models.CharField(max_length=86)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloudstack_user_ids', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
