# Generated by Django 3.2.7 on 2021-12-16 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs_api', '0003_cloudstackuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloudstackuser',
            old_name='user',
            new_name='user_id',
        ),
    ]
