# Generated by Django 3.2.7 on 2021-12-16 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs_api', '0004_rename_user_cloudstackuser_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloudstackuser',
            old_name='apiKey',
            new_name='api_key',
        ),
        migrations.RenameField(
            model_name='cloudstackuser',
            old_name='secretKey',
            new_name='secret_key',
        ),
    ]
