# Generated by Django 3.2.7 on 2021-12-16 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs_api', '0006_apirequest_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequest',
            name='cloudstack_user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='api_request_ids', to='cs_api.cloudstackuser'),
            preserve_default=False,
        ),
    ]
