# Generated by Django 3.2.7 on 2021-12-16 21:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cs_api', '0007_apirequest_cloudstack_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
