# Generated by Django 3.2.7 on 2021-12-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_api', '0008_apirequest_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudstackEventServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=300)),
                ('exchange', models.CharField(default='cloudstack-events', max_length=300)),
            ],
        ),
    ]
