# Generated by Django 3.2.7 on 2021-12-17 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs_api', '0009_cloudstackeventserver'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudstackEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routing_key', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('cloudstack_event_server_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloudstack_event_log_ids', to='cs_api.cloudstackeventserver')),
            ],
        ),
    ]
