# Generated by Django 3.2.7 on 2021-12-18 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cs_api', '0010_cloudstackeventlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudstackeventserver',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cloudstack_event_server_ids', to='auth.user'),
            preserve_default=False,
        ),
    ]
