# Generated by Django 3.2.7 on 2021-12-18 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs_api', '0011_cloudstackeventserver_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudstackEventTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloudstack_event_server_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs_api.cloudstackeventserver')),
                ('cloudstack_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs_api.cloudstackuser')),
            ],
        ),
    ]
