# Generated by Django 3.2.7 on 2021-12-18 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs_api', '0012_cloudstackeventtrigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudstackeventtrigger',
            name='cloudstack_event_server_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloudstack_event_trigger_ids', to='cs_api.cloudstackeventserver'),
        ),
        migrations.CreateModel(
            name='CloudstackEventTriggerCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_key', models.CharField(max_length=100)),
                ('operator', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=200)),
                ('cs_event_trigger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloudstack_event_trigger_condition_ids', to='cs_api.cloudstackeventtrigger')),
            ],
        ),
    ]
