# Generated by Django 3.2.7 on 2021-12-18 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs_api', '0013_auto_20211218_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudstackeventtrigger',
            name='command_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='cs_api.command'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CloudstackEventTriggerActionParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=200)),
                ('cs_event_trigger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloudstack_event_trigger_action_parameter_ids', to='cs_api.cloudstackeventtrigger')),
                ('parameter_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cs_api.parameter')),
            ],
        ),
    ]
